
CREATE TEMPORARY TABLE FREQUENCY_TABLE AS
WITH FREQUENCY AS (
    SELECT CUSTOMERNAME, COUNT(ORDERNUMBER) AS TOTAL_ORDERS 
    FROM MOTODATA 
    GROUP BY CUSTOMERNAME
)
SELECT  
    F.CUSTOMERNAME,
    F.TOTAL_ORDERS,
    NTILE(5) OVER (ORDER BY F.TOTAL_ORDERS) AS frequency_score
FROM FREQUENCY F;

select * from FREQUENCY_TABLE;




