CREATE TEMPORARY TABLE RFM_METRICS AS
select R.CUSTOMERNAME,R.recency,F.TOTAL_ORDERS,M.TOTAL_MONEY,R.recency_score,F.frequency_score,M.monetory_score FROM
RECENCY_TABLE R 
JOIN
FREQUENCY_TABLE F
ON
R.CUSTOMERNAME=F.CUSTOMERNAME
JOIN
monetory_table M
ON
F.CUSTOMERNAME=M.CUSTOMERNAME;


SELECT * FROM RFM_METRICS;

SELECT CUSTOMERNAME,RECENCY,TOTAL_ORDERS,TOTAL_MONEY,RECENCY_SCORE,FREQUENCY_SCORE,MONETORY_SCORE,(RECENCY_SCORE+FREQUENCY_SCORE+MONETORY_SCORE) AS RFM_SCORE FROM RFM_METRICS;
ALTER TABLE RFM_METRICS RENAME COLUMN MONETARY TO FREQUENCY;
SELECT * FROM RFM_METRICS;
ALTER TABLE RFM_METRICS RENAME COLUMN TOTAL_MONEY TO MONETARY;

CREATE TEMPORARY TABLE RFM_FINAL_VALUE AS
SELECT CUSTOMERNAME,RECENCY,FREQUENCY,MONETARY,RECENCY_SCORE,FREQUENCY_SCORE,MONETORY_SCORE,(RECENCY_SCORE+FREQUENCY_SCORE+MONETORY_SCORE) AS RFM_SCORE FROM RFM_METRICS;
SELECT * FROM RFM_FINAL_VALUE ORDER BY RFM_SCORE DESC;

CREATE TEMPORARY TABLE CUST_SEGMENT AS
SELECT *,
    CASE 
        WHEN rfm_score BETWEEN 12 AND 15 THEN 'Best Customers'
        WHEN rfm_score BETWEEN 8 AND 11 THEN 'Loyal Customers'
        WHEN rfm_score BETWEEN 4 AND 7 THEN 'Potential Loyalists'
        WHEN rfm_score BETWEEN 0 AND 3 THEN 'At Risk'
        ELSE 'Other'
    END AS customer_segment
FROM RFM_FINAL_VALUE ORDER BY  RFM_SCORE DESC;

SELECT * FROM CUST_SEGMENT;
